### PR TITLE
1st commitREADME.md

### PR DESCRIPTION
**Pull request by heet-2312**

### CODE REVIEW

**Comment by rishabhKalakoti** [comment]
@heet-2312 

> If possible learn Web Scrapping with Python using Scala

Web scraping with python and web scraping in scala are kind of different as they are both different languages. You sure this was what you meant to write?

**Comment by heet-2312** [comment]
sorry i was going to write scrapy,i guess i just made a mistake in writing it

**Comment by heet-2312** [comment]
@rishabhKalakoti 
So do i have to create a new commit to make modifications and then aagain create a pull request?

**Comment by rishabhKalakoti** [comment]
@heet-2312 , no need to create a new pull request, you can make a new commit in the same branch you raised the PR from, I will merge after that.

Btw, it's a good practice to never make changes in the master branch, changes should always be pushed from a fresh branch, otherwise, commits stack up and may complicate the diff, if this sounds complex, you don't have to do this right now.
Use [this](https://github.com/Codeshows/100DaysOfCode/pull/16#issuecomment-569436228) for reference.

**Comment by heet-2312** [comment]
@rishabhKalakoti  now can you merge my branch ?

**Pull request merged**
