### PR TITLE
Changed the formatting. 

### PR DESCRIPTION
**Pull request by paraggoyal28**
Previous formatting was not looking nice

### CODE REVIEW

**Comment by rishabhKalakoti** [comment]
You should also update the progress in the README day-wise and give links to the added files there itself.

**Comment by paraggoyal28** [comment]
Is there any problem in merging. Should I not commit code files. Please direct.

**Comment by rishabhKalakoti** [comment]
Here you should also add the link of the problem and the link to the solution you committed so that it is more readable and explanatory. Also, it will be better to make date a heading. Then it would be better, there are no issues with merging.
Let me give an example.

### 22 Dec 2019 (Day 1)

- Problems solved:

| Problem      | My solution           |
| ------------- |-------------|
| [ONE](https://spoj.com/problems/ONE/) (SPOJ)      | [solution](SPOJ/ONEcpp) |
| [PRIME1](https://spoj.com/problems/PRIME1/) (SPOJ) | [solution](SPOJ/PRIME1.cpp)      |

Table is just one of the ideas. Even a list is good as it is simpler. Its just better to give the link to the problem/ solution when you commit those files, which is appreciated.

**Comment by paraggoyal28** [comment]
> Here you should also add the link of the problem and the link to the solution you committed so that it is more readable and explanatory. Also, it will be better to make date a heading. Then it would be better, there are no issues with merging.
> Let me give an example.
> 
> ### 22 Dec 2019 (Day 1)
> * Problems solved:
> 
> Problem	My solution
> [ONE](https://spoj.com/problems/ONE) (SPOJ)	[solution](SPOJ/ONEcpp)
> [PRIME1](https://spoj.com/problems/PRIME1) (SPOJ)	[solution](SPOJ/PRIME1.cpp)
> Table is just one of the ideas. Even a list is good as it is simpler. Its just better to give the link to the problem/ solution when you commit those files, which is appreciated.

ok

**Comment by paraggoyal28** [comment]
please check now

**Comment by rishabhKalakoti** [comment]
Please change the links to your solution to relative links which point to the solution in the PR, right now it points to the files in your copy of the fork. You can incorporate these changes the next time you raise make an update. I am merging the PR for now. Good Job!

**Pull request merged**
